### ISSUE TITLE
panel symbols

### ISSUE THREAD

**Issue by ch-sander** [lombardpress/lombardpress-webjs#108]
![grafik](https://user-images.githubusercontent.com/74921235/159881934-8d316d03-b765-41be-995e-5e7fcd05f5cc.png)

I think it's too difficult to navigate only by the symbols. They need at least a tooltip text at hover event

**Comment by jeffreycwitt** [comment]
Many many thanks for this issue.

There was a bug preventing the primitive tool tip I already had in place from working. I didn't know it stopped working.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/1146685/169922969-9892bfdc-d1e5-4d6e-af0b-eda0c8950de2.png">

It should work now. 

I don't know about the order. I'm not sure why one ordering makes more sense than the other.

If it really does matter, let's make a separate issue and discuss why it matters. 

Since this issue is primarily about the tool tip I'll consider it closed as of commit adc3863caca7cadb1c558accfe11e01c94a29be5

**Comment by ch-sander** [comment]
As for the order: it's not "important", the order I proposed is just what I would expect and think is more intuitive. But your intuitition is different here, let's keep it this way.
